name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            DesignConnect/DesignConnect/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('DesignConnect/DesignConnect/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        working-directory: DesignConnect/DesignConnect
        run: |
          npm ci --prefer-offline --no-audit
        env:
          CI: true

      - name: Build
        working-directory: DesignConnect/DesignConnect
        run: |
          npm run build
        env:
          CI: true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Check build output
        run: |
          ls -la DesignConnect/DesignConnect/dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: DesignConnect/DesignConnect/dist
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2